plugins {
    id 'com.android.application'
}

android {
    namespace 'com.cosmogram.app'
    compileSdk 34

    defaultConfig {
        applicationId 'com.cosmogram.app'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    def keystorePropertiesFile = rootProject.file('keystore.properties')
    def keystoreProperties = new Properties()
    if (keystorePropertiesFile.exists()) {
        keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
    }

    signingConfigs {
        release {
            storeFile rootProject.file('cosmogram-release.keystore')
            storePassword keystoreProperties['PASSWORD']
            keyAlias 'cosmogram'
            keyPassword keystoreProperties['PASSWORD']
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
}
